### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim10#1]
Nije sistemskih nego softverskih

**Comment by mirelapeskovic** [comment]
Ispravili smo ovo. Nas samo buni zašto ne može sistemskih jer smo na SI-u razliku između sistema i softvera definisali kao da je sistem specifikacija i hardvera, i td.

**Comment by deancupovic** [comment]
System requirements specification - IEEE 1233
Software requirements specification - IEEE 830
