### ISSUE TITLE
Kod?

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim10#18]
Šta je sa kodom, rekli smo da ćete imati forme do 1. maja?

**Comment by mirelapeskovic** [comment]
Mi smo mislili da trebamo ispraviti dokument dizajn korisničkog interfejsa i postaviti do 1.maja , ali svakako smo radili u eclipse-u, možemo li postaviti večeras dokument sa projektom ?

**Comment by deancupovic** [comment]
postavite
