### ISSUE TITLE
init.sql se ne može importovati, aplikacija se ne može pokrenuti

### ISSUE THREAD

**Issue by ragibsmajic** [SoftverInzenjeringETFSA/SI2015Tim10#19]
Prilikom pokušaja importa init.sql pojavljuje se sljedeća greška:
Error
## -- Table structure for table `kategorija`

DROP TABLE IF EXISTS `kategorija`;
MySQL said: Documentation
#1046 - Aucune base n'a Ã©tÃ© sÃ©lectionnÃ©e

Init.sql sam našao u folderu Implementacija, nisam siguran je li to pravi jer nema nigdje naznačeno koji jeste.

**Comment by spica29** [comment]
probaj sad init.sql, prvo import u shemu tim10, napravis usera EtfSI2015 pw: 2015SIEtf i onda pokreni App.java. Username i pw ce odmah biti u tabelama nismo hesirali.
