### ISSUE TITLE
Zatvaranje prozora u kojem se briše kategorija zatvara aplikaciju

### ISSUE THREAD

**Issue by apalavra1** [SoftverInzenjeringETFSA/SI2015Tim10#24]
Komponenta:
Interfejs za menadžera

Commit id:
e4b6488a7d749cd40010bda2dc20d92ba33d2f75

Opis problema:
Nakon što uspješno obrišemo kategoriju i želimo se vratiti na interfejs za menadžera zatvaranjem prozora u kojem se briše kategorija, zatvara se i aplikacija.(Close umjesto dispose).

Koraci za reproduciranje problema:
1. Otvoriti desktop aplikaciju SiDesk
2. Logovati se kao menadžer
3. Kliknuti na "Ažuriraj kategorije"
4. Odabrati "Obriši kategoriju"
5. Unijeti ispravne podatke
6. Kliknuti na "Obriši kategoriju"
7. Zatvoriti poruku o uspješnom brisanju kategorije
8. Zatvoriti prozor u kojem se unosi kategorija za brisanje

Dobijeni rezultat:
Zatvara se aplikacija u potpunosti.

Screenshot 1:
![brisanje kategorije prije](https://cloud.githubusercontent.com/assets/11329025/15332551/5ca3eafa-1c66-11e6-913c-c9bb0760a6e5.jpg)

Screenshot 2:
![brisanje kategorije zatvara aplikaciju](https://cloud.githubusercontent.com/assets/11329025/15332581/76c88c24-1c66-11e6-8123-8d05b20438b4.jpg)

Očekivani rezultat:
Povratak na početni interfejs za menadžera.

**Comment by avelija1** [comment]
Ispravljeno
