### ISSUE TITLE
Moguća pojava korisnika sa istim korisničkim imenom

### ISSUE THREAD

**Issue by ragibsmajic** [SoftverInzenjeringETFSA/SI2015Tim10#25]
Opis:

Prilikom izmjene podataka korisnika moguće je da različiti korisnici imaju isti username. 

Koraci za reproduciranje problema:
1. Otvoriti administratorski prozor
2. Napraviti izmjene podataka za nekog korisnika, postaviti username i password na user i pass
3. Odabrati drugog korisnika i napraviti istu stvar

Očekivano:

Očekuje se da sistem prijavi grešku kako korisnik sa takvim usernameom već postoji, te da treba biti odabrano neko drugo.

**Comment by avelija1** [comment]
Ispravljeno
