### ISSUE TITLE
Prilikom zatvaranja prozora za dodavanje korisnika na X zatvara se aplikacija

### ISSUE THREAD

**Issue by ragibsmajic** [SoftverInzenjeringETFSA/SI2015Tim10#26]
Opis:

Prilikom zatvaranja prozora za dodavanje korisnika, zatvara se aplikacija.

Koraci za reproduciranje problema:
1. Otvoriti administratorski prozor
2. Kliknuti na dugme dodaj novog
3. Zatvoriti formu koja se otvorila na X, ne na dugme za izlaz

Očekivano:

Očekuje se da se samo forma za dodavanje novog korisnika zatvori, a ne cijela aplikacija.

**Comment by avelija1** [comment]
Ispravljeno
