### ISSUE TITLE
Moguće je otvoriti istovremeno više od jednog prozora i za dodavanje, brisanje i za ažuriranje kategorija

### ISSUE THREAD

**Issue by ragibsmajic** [SoftverInzenjeringETFSA/SI2015Tim10#27]
Opis

Moguće je otvoriti istovremeno više od jednog prozora i za dodavanje i za brisanje i za ažuriranje kategorija, što može dovesti do nekonzistentnosti podataka u sistemu. 

Koraci za reproduciranje problema:
1. Otvoriti formu za menadžere
2. Otvarati forme za dodavanje, brisanje i azuriranje kategorija bez zatvaranja prethodno otvorenih

Očekivano:

Očekuje se da glavna forma nije dostupna dok se forma za npr. dodavanje kategorije ne zatvori.

**Comment by enverpezic** [comment]
ispravljeno
