### ISSUE TITLE
Zatvaranje prozora u kojem se mijenjaju podaci o korisniku zatvara aplikaciju

### ISSUE THREAD

**Issue by apalavra1** [SoftverInzenjeringETFSA/SI2015Tim10#30]
Komponenta:
Interfejs za admina

Commit id:
e4b6488a7d749cd40010bda2dc20d92ba33d2f75

Opis problema:
Nakon što uspješno izmijenimo podatke o korisniku i želimo se vratiti na interfejs za admina zatvaranjem prozora u kojem se mijenjaju podaci o korisniku, zatvara se i aplikacija.(Close umjesto dispose).

Koraci za reproduciranje problema:
1. Otvoriti desktop aplikaciju SiDesk
2. Logovati se kao admin
3. Odabrati Admin kao "Tip korisnika"
4. Kliknuti na "Izmjeni"
5. Unijeti ispravne podatke
6. Kliknuti na "Spasi izmjene"
7. Zatvoriti prozor za izmjenu podataka o korisniku

Dobijeni rezultat:
Zatvara se aplikacija u potpunosti.

Screenshot:
![spasavanje izmjena](https://cloud.githubusercontent.com/assets/11329025/15336387/b0785494-1c76-11e6-8121-159d64703e82.jpg)

Očekivani rezultat:
Povratak na početni interfejs za admina.

**Comment by avelija1** [comment]
Ispravljeno
