### ISSUE TITLE
Nejasne informacije o nepravilnostima prilikom popunjavanja u formama

### ISSUE THREAD

**Issue by amarbasic** [SoftverInzenjeringETFSA/SI2015Tim10#33]
Komponenta:
Administrator dodaj novog korisnika

commit ID:
59c9ae9

Opis problema:
Prilikom unosa podataka, iako se popune sva polja dobije se poruka "Unijeli ste pogresne podatek". Nije jasno koji podaci nisu dobro uneseni i kakvog formata bi trebali biti.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju i prijaviti se kao administrator
2. Sa admin forme izabrati opciju za dodavanje novog korisnika
3. Popuniti sva polja
4. Kliknuti na "Dodaj korisnika"

Dobijeni rezultat:
- Messagebox "Unijeli ste pogresne podatke" (screenshot).

![image](https://cloud.githubusercontent.com/assets/11327911/15351211/790316ee-1cde-11e6-8f96-b3f1c24688fc.png)

![image](https://cloud.githubusercontent.com/assets/11327911/15351228/8d676ca2-1cde-11e6-830d-a227bc79805a.png)

Očekivani rezultat:
- Trebalo bi korisnika obavjestiti šta nije tačno uneseno i u kojem formatu bi trebalo biti.

**Comment by avelija1** [comment]
Ispravljeno
