### ISSUE TITLE
Administrator može obrisati sam sebe

### ISSUE THREAD

**Issue by amarbasic** [SoftverInzenjeringETFSA/SI2015Tim10#34]
Komponenta:
Brisanje korisnika

commit ID:
59c9ae9

Opis problema:
Prilikom brisanja korisnika administrator može obrisati sam sebe.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju i prijavti se kao administrator
2. Pretražiti sve administratore
3. Odabrati sebe, tj. trenutno prijavljenog korisnika
4. Kliknuti na "Obriši"

Dobijeni rezultat:
- Obavještenje o uspješno brisanju korisnika.

Očekivani rezultat:
- Trebalo bi se prijaviti greška da korisnik briše sam sebe.

**Comment by avelija1** [comment]
Ispravljeno.
