### ISSUE TITLE
Prilikom dodavnja novog korisnika moguce unijeti email sa *@example.com

### ISSUE THREAD

**Issue by amarbasic** [SoftverInzenjeringETFSA/SI2015Tim10#36]
Komponenta:
Kreiranje korisnika

commit ID:
59c9ae9

Opis problema:
Prilikom kreiranja korisnika moguće je unijeti email oblika *@example.com

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju i prijaviti se kao administrator
2. Kliknuti na "Dodaj novog"
3. Unijesti ispravne podatke osim email-a
4. Kliknuti na dodaj korisnika

Dobijeni rezultat:
- Dobije se obavještenje o uspješnom kreiranju korisnika (screenshot).

![image](https://cloud.githubusercontent.com/assets/11327911/15352302/d5654178-1ce3-11e6-80bd-8beca11b8245.png)

![image](https://cloud.githubusercontent.com/assets/11327911/15352315/e29491a0-1ce3-11e6-9157-492adb0a7062.png)

Očekivani rezultat:
- Ne bi trebalo dozvoliti da se kreira email koji sadrži specijalne karaktere.

**Comment by avelija1** [comment]
ispravljeno
