### ISSUE TITLE
Neusaglašenost SRSa i dizajna - Dodavanje korisnika - Jedinstvenost polja

### ISSUE THREAD

**Issue by amarbasic** [SoftverInzenjeringETFSA/SI2015Tim10#38]
Komponenta:
Dodavanje korisnika

commit ID:
59c9ae9

Opis problema:
1. U SRS-u je navedeno da prilikom dodavnja korisnika potrebno navesti sljedeće podatke

![image](https://cloud.githubusercontent.com/assets/11327911/15352923/d7348fb0-1ce6-11e6-88d1-69121deb77b8.png)

Međutim, na formi postoje i dodatna polja.
1. U SRS-u je navedeno sljedeća polja moraju biti jedinstvena:

![image](https://cloud.githubusercontent.com/assets/11327911/15352966/0f9b724c-1ce7-11e6-9d25-7d9eb2466543.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju i prijaviti se kao administrator
2. Kliknuti na "Dodaj novog"
3. Popuniti sva polja prema uslovima validnosti u SRS-u

Dobijeni rezultat:
- Javlja se greška da korisnik postoji

Očekivani rezultat:
- Korisnik se treba dodati jer ne postoji takav

Rješenje:
- U kodu vam je uslov da i pretraga po imenu mora biti null, a prema SRS-u ime se može ponavljati.

![image](https://cloud.githubusercontent.com/assets/11327911/15353092/88f6b87c-1ce7-11e6-83d1-b47a20edef3a.png)

**Comment by avelija1** [comment]
Ispravljeno.
