### ISSUE TITLE
Neusaglašenost SRSa i koda - Promjena lozinke

### ISSUE THREAD

**Issue by amarbasic** [SoftverInzenjeringETFSA/SI2015Tim10#39]
Komponenta:
Promjena šifre

commit ID:
59c9ae9

Opis problema:
U SRS-u je navedno da svaki korisnik ima mogućnost promjene šifre. Ta funkcionalnost uopće ne postoji,

![image](https://cloud.githubusercontent.com/assets/11327911/15353284/98057e10-1ce8-11e6-91d6-e458d6e94a92.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju i prijaviti se npr. kao menadžer
2. Ne postoji opcija za promjenu šifre.

Dobijeni rezultat:
- Nema rezultata. Ne postoji funkcionalnost

Očekivani rezultat:
- Trebalo bi svaki prijavljeni korisnik ima mogućnost promjene šifre kako je to nevedno u SRS-u, a ne da samo administrator može mijenjati šifre.

**Comment by spica29** [comment]
ipak smo na kraju odlucili da samo admin mijenja sifre
