### ISSUE TITLE
Neusaglašenost SRS-a i koda: Menadžer nema mogućnost modifikacije ni brisanja postojećeg klijenta

### ISSUE THREAD

**Issue by apalavra1** [SoftverInzenjeringETFSA/SI2015Tim10#45]
Komponente:
Funkcionalnosti korisnika sa privilegijom menadžera
Dokuments SRS ispravka

Commit id: 
59c9ae9fbd47310b68ff95997905bddff7cde91b

Opis problema:
U SRS-u je navedeno da korisnik sa privilegijama menadžera ima mogućnosti modifikacije i brisanja klijenata koji su već ranije zavedeni u sistem. To su funkcionalni zahtjevi 3.2.15 i 3.2.16. Aplikacija ne omogućava menadžeru modifikaciju ni brisanje postojećih klijenata.

Screenshot-ovi:
![3 2 15](https://cloud.githubusercontent.com/assets/11329025/15357281/1ca19126-1cfe-11e6-9586-3464626f5340.jpg)

![3 2 16](https://cloud.githubusercontent.com/assets/11329025/15357287/22770946-1cfe-11e6-80c8-be18453bfbe5.jpg)

**Comment by spica29** [comment]
u ovoj fazi bi oduzelo previše vremena za implementaciju ove dvije funkcionalnosti
