### ISSUE TITLE
Loše porvatne informacije prilikom pravljenja scenarcija

### ISSUE THREAD

**Issue by amarbasic** [SoftverInzenjeringETFSA/SI2015Tim10#48]
Komponenta:
Korisnik - dodavanje korisnika, scenarija

commit ID:
bff68bb

Opis problema:
Prilikom pravljenja scenarija i dodavanja korisnika dobiju se loše povratne informacije da nešto nije ispravno uneseno. Samim ti ne ne mogu uopće da testiram aplikaciju dalje jer mi ne prolazi niti jedan način dodavanja korisnika i pravljenje scenarija

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju prijaviti se kao obicni korisnik
2. Unijeti podatke novog korisnika (screenshot)

![image](https://cloud.githubusercontent.com/assets/11327911/15387141/b4c7fcda-1dab-11e6-9c8b-d32bc35e1166.png)
1. Odabrati scenarij (screenshot)

![image](https://cloud.githubusercontent.com/assets/11327911/15387160/caaa70be-1dab-11e6-885c-3c95631ac6a7.png)
1. Završiti scenarij sa opisom (screenshot)

![image](https://cloud.githubusercontent.com/assets/11327911/15387167/dfae0d2c-1dab-11e6-8697-0ea96f7c104f.png)

Dobijeni rezultat:
- Obavještenje da su podaci uneseni pogrešno (screenshot)

![image](https://cloud.githubusercontent.com/assets/11327911/15387178/f5b2c810-1dab-11e6-901d-fe515946c939.png)

Očekivani rezultat:
- Korisnik ne zna gdje je unio pogrešne podatke pa tako ni ja sada.

**Comment by spica29** [comment]
Podrazumijeva se da korisnik zna da ako označi pitanje u tabeli, ne može označiti izlazak iz scenarija (jer samo jedno od to dvoje može proći, ali ne i oboje). Ima ovdje napisano:
http://pokit.org/get/?b2b0fffef7a21c802db8b95802ab10e7.jpg
