### ISSUE TITLE
Moguće unijeti korisnika bez imena i prezimena, broja LK i passworda

### ISSUE THREAD

**Issue by goroFaruk** [SoftverInzenjeringETFSA/SI2015Tim10#49]
Komponenta:
Dodavanje Novog Korisnika

commit id:
42cf524

Opis problema:
Moguće je unijeti korisnika bez imena i prezimena, bez generisanja lozinke, te bez broja LK. Loša validacija.

![dodavanjekorisnika](https://cloud.githubusercontent.com/assets/17453090/15440998/aff5b426-1ed8-11e6-84ec-07ee41c4b8a2.jpg)

Koraci za reprodukciju problema:
1. Pokrenuti desktop aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na "Dodaj Novog Korisnika"
4. Popuniti formu kao na slici iznad
5. Kliknuti na dugme "Dodaj Korisnika"

-Dobijeni rezultat 
 Korisnik uspješno dodan

-Očekivan rezultat
 Greška pri unosu podataka

**Comment by avelija1** [comment]
ispravljeno
