### ISSUE TITLE
Dva korisnika sa istim brojem LK 

### ISSUE THREAD

**Issue by goroFaruk** [SoftverInzenjeringETFSA/SI2015Tim10#50]
Komponenta:
UređivanjeKorisnika

commit id:
 42cf524

Opis problema:
Prilikom modifikacije korisnika, moguće je korisniku dodijeliti isti broj lične karte, kao kod korisnika koji već postoji  u bazi podataka.

Koraci za reprouciranje problema:
1. Pokrenuti desktop aplikaciju
2. Prijaviti se kao administrator
3. Za tip korisnika odabrati Administrator i kliknuti na ikonu pretraži
4. Odabrati nekog korisnika
5. Kliknuti na dugme Izmjeni
6. U polje Br. lične karte otkucati broj lične karte postojećeg korisnika iz baze podataka
7. Kliknuti na Spasi izmjene

Dobijeni rezultat:
 Korisnik uspješno dodan

Očekivani rezultat
 Greška pri unosu podataka

**Comment by avelija1** [comment]
Ispravljeno
